# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Table(object):
    def setupUi(self, Table,mainWindow):
        Table.setObjectName("Table")
        Table.resize(537, 433)
        self.gridLayout = QtWidgets.QGridLayout(Table)
        self.gridLayout.setObjectName("gridLayout")
        self.labelOriginal = QtWidgets.QLabel(Table)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelOriginal.setFont(font)
        self.labelOriginal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOriginal.setObjectName("labelOriginal")
        self.gridLayout.addWidget(self.labelOriginal, 0, 0, 1, 1)
        self.tableOriginal = QtWidgets.QTableWidget(Table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableOriginal.sizePolicy().hasHeightForWidth())
        self.tableOriginal.setSizePolicy(sizePolicy)
        self.tableOriginal.setMinimumSize(QtCore.QSize(265, 70))
        self.tableOriginal.setColumnCount(2)
        self.tableOriginal.setObjectName("tableOriginal")
        self.tableOriginal.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableOriginal.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(97, 124, 118))
        self.tableOriginal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(97, 124, 118))
        self.tableOriginal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOriginal.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOriginal.setItem(0, 1, item)
        self.gridLayout.addWidget(self.tableOriginal, 1, 0, 1, 1)
        self.labelDTW = QtWidgets.QLabel(Table)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDTW.setFont(font)
        self.labelDTW.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDTW.setObjectName("labelDTW")
        self.gridLayout.addWidget(self.labelDTW, 2, 0, 1, 1)
        self.tableDTW = QtWidgets.QTableWidget(Table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableDTW.sizePolicy().hasHeightForWidth())
        self.tableDTW.setSizePolicy(sizePolicy)
        self.tableDTW.setMinimumSize(QtCore.QSize(515, 70))
        self.tableDTW.setObjectName("tableDTW")
        self.tableDTW.setColumnCount(4)
        self.tableDTW.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("PMS")
        font = QtGui.QFont()
        font.setKerning(False)
        item.setFont(font)
        self.tableDTW.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableDTW.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDTW.setItem(0, 3, item)
        self.gridLayout.addWidget(self.tableDTW, 3, 0, 1, 1)
        self.labelCOW = QtWidgets.QLabel(Table)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCOW.setFont(font)
        self.labelCOW.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCOW.setObjectName("labelCOW")
        self.gridLayout.addWidget(self.labelCOW, 4, 0, 1, 1)
        self.tableCOW = QtWidgets.QTableWidget(Table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCOW.sizePolicy().hasHeightForWidth())
        self.tableCOW.setSizePolicy(sizePolicy)
        self.tableCOW.setMinimumSize(QtCore.QSize(515, 70))
        self.tableCOW.setObjectName("tableCOW")
        self.tableCOW.setColumnCount(4)
        self.tableCOW.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCOW.setItem(0, 3, item)
        self.gridLayout.addWidget(self.tableCOW, 5, 0, 1, 1)
        self.labelPTW = QtWidgets.QLabel(Table)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelPTW.setFont(font)
        self.labelPTW.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPTW.setObjectName("labelPTW")
        self.gridLayout.addWidget(self.labelPTW, 6, 0, 1, 1)
        self.tablePTW = QtWidgets.QTableWidget(Table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablePTW.sizePolicy().hasHeightForWidth())
        self.tablePTW.setSizePolicy(sizePolicy)
        self.tablePTW.setMinimumSize(QtCore.QSize(515, 70))
        self.tablePTW.setObjectName("tablePTW")
        self.tablePTW.setColumnCount(4)
        self.tablePTW.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePTW.setItem(0, 3, item)
        self.gridLayout.addWidget(self.tablePTW, 7, 0, 1, 1)

        self.load(mainWindow)
        Table.setWindowState(Table.windowState() & ~QtCore.Qt.WindowMinimized | QtCore.Qt.WindowActive)
        Table.activateWindow()
        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def load(self, mainWindow):
        evOr = mainWindow.evaluateOriginal()
        item = self.tableOriginal.item(0, 0)
        item.setText(str(evOr[0]))
        item = self.tableOriginal.item(0, 1)
        item.setText(str(evOr[1]))

        evDTW = mainWindow.evaluateDTW()
        item = self.tableDTW.item(0, 0)
        item.setText(str(evDTW[0]))
        item = self.tableDTW.item(0, 1)
        item.setText(str(evDTW[1]))
        item = self.tableDTW.item(0, 2)
        item.setText(str(evDTW[2]))
        item = self.tableDTW.item(0, 3)
        item.setText(str(evDTW[3]))

        evCOW = mainWindow.evaluateCOW()
        item = self.tableCOW.item(0, 0)
        item.setText(str(evCOW[0]))
        item = self.tableCOW.item(0, 1)
        item.setText(str(evCOW[1]))
        item = self.tableCOW.item(0, 2)
        item.setText(str(evCOW[2]))
        item = self.tableCOW.item(0, 3)
        item.setText(str(evCOW[3]))

        evPTW = mainWindow.evaluatePTW()
        item = self.tablePTW.item(0, 0)
        item.setText(str(evPTW[0]))
        item = self.tablePTW.item(0, 1)
        item.setText(str(evPTW[1]))
        item = self.tablePTW.item(0, 2)
        item.setText(str(evPTW[2]))
        item = self.tablePTW.item(0, 3)
        item.setText(str(evPTW[3]))


    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Form"))
        self.labelOriginal.setText(_translate("Table", "Original Signal"))
        item = self.tableOriginal.horizontalHeaderItem(0)
        item.setText(_translate("Table", "Correlation"))
        item = self.tableOriginal.horizontalHeaderItem(1)
        item.setText(_translate("Table", "RMS"))
        __sortingEnabled = self.tableOriginal.isSortingEnabled()
        self.tableOriginal.setSortingEnabled(False)
        self.tableOriginal.setSortingEnabled(__sortingEnabled)
        self.labelDTW.setText(_translate("Table", "DTW Results"))
        item = self.tableDTW.horizontalHeaderItem(0)
        item.setText(_translate("Table", "Correlation"))
        item = self.tableDTW.horizontalHeaderItem(1)
        item.setText(_translate("Table", "RMS"))
        item = self.tableDTW.horizontalHeaderItem(3)
        item.setText(_translate("Table", "Time"))
        __sortingEnabled = self.tableDTW.isSortingEnabled()
        self.tableDTW.setSortingEnabled(False)
        self.tableDTW.setSortingEnabled(__sortingEnabled)
        self.labelCOW.setText(_translate("Table", "COW Results"))
        item = self.tableCOW.horizontalHeaderItem(0)
        item.setText(_translate("Table", "Correlation"))
        item = self.tableCOW.horizontalHeaderItem(1)
        item.setText(_translate("Table", "RMS"))
        item = self.tableCOW.horizontalHeaderItem(2)
        item.setText(_translate("Table", "PMS"))
        item = self.tableCOW.horizontalHeaderItem(3)
        item.setText(_translate("Table", "Time"))
        __sortingEnabled = self.tableCOW.isSortingEnabled()
        self.tableCOW.setSortingEnabled(False)

        self.tableCOW.setSortingEnabled(__sortingEnabled)
        self.labelPTW.setText(_translate("Table", "PTW Results"))
        item = self.tablePTW.horizontalHeaderItem(0)
        item.setText(_translate("Table", "Correlation"))
        item = self.tablePTW.horizontalHeaderItem(1)
        item.setText(_translate("Table", "RMS"))
        item = self.tablePTW.horizontalHeaderItem(2)
        item.setText(_translate("Table", "PMS"))
        item = self.tablePTW.horizontalHeaderItem(3)
        item.setText(_translate("Table", "Time"))
        __sortingEnabled = self.tablePTW.isSortingEnabled()
        self.tablePTW.setSortingEnabled(False)

        self.tablePTW.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table = QtWidgets.QWidget()
    ui = Ui_Table()
    ui.setupUi(Table)
    Table.show()
    sys.exit(app.exec_())
